### ISSUE TITLE
Login page is not rendered

### ISSUE THREAD

**Issue by tienvx** [api-platform/admin#235]
How to reproduce:
1. Make sure your API is protected by security (especially /api/docs.jsonld)
2. Update API Platform Admin to v1.0.0
3. Start admin

Expected: Login page is rendered
Actual: A blank page with `Error while reading the API schema`

On the browser's console:
```
GET https://{api_url}/api/docs.jsonld 401 (Unauthorized)
```

**Comment by dunglas** [comment]
Fixed in the latest tag!

**Comment by ldbglobe** [comment]
Still buggy with current documentation and the previous solutions seems to not work anymore 😭

My solution rely on the native AUTH_ERROR and AUTH_CHECK procedure handled by react-amin app

apiDocumentationParser does not execute any reponse status test and the authProvider do some verification for us (and react-admin do the trick for us)
```js
const apiDocumentationParser = entrypoint => parseHydraDocumentation(entrypoint, { headers: new Headers(fetchHeaders) })
```

My final code (do not forget to replace entrypoint and login url by your own) 😁

```js
// in src/App.js
import React from 'react';
import { HydraAdmin } from '@api-platform/admin';
import parseHydraDocumentation from '@api-platform/api-doc-parser/lib/hydra/parseHydraDocumentation';
import { dataProvider as baseDataProvider, fetchHydra as baseFetchHydra  } from '@api-platform/admin';
import authProvider from './authProvider';
import { Redirect } from 'react-router-dom';

const entrypoint = "http://localhost/api"; // put your own api entry point url here

const fetchHeaders = {'Authorization': `Bearer ${window.localStorage.getItem('token')}`};
const fetchHydra = (url, options = {}) => baseFetchHydra(url, {
    ...options,
    headers: new Headers(fetchHeaders),
});
const apiDocumentationParser = entrypoint => parseHydraDocumentation(entrypoint, { headers: new Headers(fetchHeaders) })
const dataProvider = baseDataProvider(entrypoint, fetchHydra, apiDocumentationParser);

export default props => (
    <HydraAdmin
        apiDocumentationParser={ apiDocumentationParser }
        dataProvider={ dataProvider }
        authProvider={ authProvider }
        entrypoint={ entrypoint }
    />
);
```

```js
// in src/authProvider.js
import { AUTH_LOGIN, AUTH_LOGOUT, AUTH_ERROR, AUTH_CHECK } from 'react-admin';

// Change this to be your own login check route.
const login_uri = "http://localhost/login"; //put your own login url here

export default (type, params) => {
  switch (type) {
    case AUTH_LOGIN:
      const { username, password } = params;
      const request = new Request(`${login_uri}`, {
        method: 'POST',
        body: JSON.stringify({ email: username, password }),
        headers: new Headers({ 'Content-Type': 'application/json' }),
      });

      return fetch(request)
        .then(response => {
          if (response.status < 200 || response.status >= 300) throw new Error(response.statusText);

          return response.json();
        })
        .then(({ token }) => {
          localStorage.setItem('token', token); // The JWT token is stored in the browser's local storage
          window.location.replace('/');
        });

    case AUTH_LOGOUT:
      localStorage.removeItem('token');
      break;

    case AUTH_ERROR:
      if (401 === params.status || 403 === params.status) {
        localStorage.removeItem('token');

        return Promise.reject();
      }
      break;

    case AUTH_CHECK:
      return localStorage.getItem('token') ? Promise.resolve() : Promise.reject();

      default:
          return Promise.resolve();
  }
}
```

**Comment by Pixadelic** [comment]
I was struggling a lot until I met your comment @ldbglobe. So thanks for sharing your solution that works well in my case!
